### PR TITLE
improve error messages

### PR DESCRIPTION
**Pull request by ScottDowne**

### CODE REVIEW

**Comment by ScottDowne** [comment]
R?

**Comment by ScottDowne** [comment]
See #20 for more info.

**Comment by alicoding** [comment]
@ScottDowne can you compile all these messages and send them to me or if you know the process of sending them to our contractor to get this translate ASAP?

**Comment by alicoding** [comment]
Unless these already part of the document that we recently sent to our contractor? cc @shaghdoosti @secretrobotron

**Comment by shaghdoosti** [comment]
No these weren't - can you send them to me ASAP please? I'll send them to the contractor.

**Comment by ScottDowne** [comment]
@shaghdoosti I filed a ticket specifically for this so it doesn't get lost: https://github.com/mozilla/petitions.mozilla.org/issues/29

**Pull request merged**
