### PR TITLE
[fix bug 1243551] Add GA to data privacy day page.

### PR DESCRIPTION
**Pull request by jpetto**
This should merge and go out to production as soon as possible.

Thanks!

### CODE REVIEW

**Comment by jpetto** [comment]
cc @jbuck

**Comment by jbuck** [comment]
There's some irony in using GA on a data privacy day page ;)

I'll get this up shortly

**Comment by jpetto** [comment]
Officially, we don't collect any user-identifiable information. But yes, much irony. Sad, sad irony. :disappointed:

**Comment by jbuck** [comment]
Deployed to production

**Pull request merged**
