### PR TITLE
Temporary removal of FB share button from data privacy day page.

### PR DESCRIPTION
**Pull request by jpetto**
- Will re-add FB button when server/scraping issues are sorted.

**Should merge and push to production only if #113 is not resolved by 1/28.**

### CODE REVIEW

**Comment by jbuck** [comment]
@jpetto good idea. Is there a particular time tomorrow that this should be pushed by if #113 hasn't been solved?

**Comment by jpetto** [comment]
Ah, was just informed the campaign will begin at 6pm PST today, so, might as well merge this one before the next prod push.

Thanks @jbuck!

**Comment by jbuck** [comment]
@jpetto okay, I'll merge and push this now. If I figure out the facebook share problem I'll update #113

**Comment by jbuck** [comment]
pushed to production

**Pull request merged**
